language: android
jdk: oraclejdk8
branches:
  only:
  - master
script: "./gradlew clean assembleDebug"
android:
  components:
  - platform-tools
  - tools
  - build-tools-29.0.2
  - android-29
  - extra-android-m2respository
before_install:
- openssl aes-256-cbc -K $encrypted_8d6af12bbf12_key -iv $encrypted_8d6af12bbf12_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
